version: '2'
services:
  elasticsearch:
    image: 'docker.elastic.co/elasticsearch/elasticsearch:6.6.0'
    ports:
      - '9200:9200'
      - '9300:9300'
    environment:
      discovery.type: single-node
  kibana:
    image: 'docker.elastic.co/kibana/kibana:6.6.0'
    ports:
      - '5601:5601'
    environment:
      ELASTICSEARCH_HOSTS: 'http://elasticsearch:9200'
  apm-server:
    image: 'docker.elastic.co/apm/apm-server:6.6.0'
    ports:
      - '8200:8200'
    volumes:
      - './apm-server.yml:/usr/share/apm-server/apm-server.yml'
